### ISSUE TITLE
QGis 3.14 : Erreur sur l'import du module postgis

### ISSUE THREAD

**Issue by lpofredc** [lpoaura/PluginQGis-LPOData#5]
Dans QGIS 3.14, la class `postgis` de `processing.tools` n'est plus comme évoqué dans ce commit.

https://github.com/qgis/QGIS/commit/4edc7d11d95875431ac9ec3d730d192e5306f108#diff-2fa32fc853cf33496bfdd34f6cb89b40

```
2020-06-30T21:52:23     CRITICAL    Traceback (most recent call last):
              File "/usr/lib/python3/dist-packages/qgis/utils.py", line 312, in loadPlugin
              __import__(packageName)
              File "/usr/lib/python3/dist-packages/qgis/utils.py", line 743, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "/home/fcloitre/.local/share/QGIS/QGIS3/profiles/default/python/plugins/scripts_lpo/__init__.py", line 27, in 
              from .scripts_lpo import ScriptsLPOPlugin
              File "/usr/lib/python3/dist-packages/qgis/utils.py", line 743, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "/home/fcloitre/.local/share/QGIS/QGIS3/profiles/default/python/plugins/scripts_lpo/scripts_lpo.py", line 34, in 
              from .scripts_lpo_provider import ScriptsLPOProvider
              File "/usr/lib/python3/dist-packages/qgis/utils.py", line 743, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "/home/fcloitre/.local/share/QGIS/QGIS3/profiles/default/python/plugins/scripts_lpo/scripts_lpo_provider.py", line 33, in 
              from .extract_data import ExtractData
              File "/usr/lib/python3/dist-packages/qgis/utils.py", line 743, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "/home/fcloitre/.local/share/QGIS/QGIS3/profiles/default/python/plugins/scripts_lpo/extract_data.py", line 49, in 
              from processing.tools import postgis
             ImportError: cannot import name 'postgis'
```

**Comment by eguilley** [comment]
cf. https://github.com/lpoaura/PluginQGis-LPOData/issues/39#issue-765185647
